name: 🐛 Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run `purgo-cli clean`
        2. See error...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Run `purgo-cli --version`
      placeholder: "1.0.3"
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "Windows 11, Node.js 20.x"
    validations:
      required: true

