blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/andrebpessoa/purgo-cli/discussions
    about: Ask questions, share ideas, or discuss with the community
  - name: 📚 Documentation
    url: https://github.com/andrebpessoa/purgo-cli#readme
    about: Read the documentation and examples
  - name: 🔒 Security Issue
    url: mailto:andrebpessoa09@gmail.com
    about: Report a security vulnerability privately

