name: ✨ Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: Describe the problem or use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage example
      placeholder: |
        purgo-cli clean --new-feature
      render: bash

